### ISSUE TITLE
Slashes in keys are urlencoded when creating signed URL

### ISSUE THREAD

**Issue by hanshuebner** [xach/zs3#12]
Basically, everything is described here: http://stackoverflow.com/questions/15473582/amazon-s3-presigned-urls-escape-the-slashes-in-the-key  -  ZS3, like some common Java libraries, urlencodes the key (and the bucket, sub-resource) when generating a signed path, which basically results all path components to be folded into the pathname of the resulting URL.  That causes the issues when particular file names are desired for files downloaded from S3.

Do you have any thoughts regarding this?  I'm inclined to remove the url-encode invocations from signed-path and authorized-url, but maybe you have a specific reason why all components are URL encoded.

**Comment by xach** [comment]
Happy coincidence: This will be fixed as part of the AWS4 auth updates.

**Comment by xach** [comment]
Fixed in 1.2.8.
