### ISSUE TITLE
Frankfurt? (or AWS4-HMAC-SHA256)

### ISSUE THREAD

**Issue by exquisitus** [xach/zs3#15]
Can you work with a bucket located in the eu-central region? I think this region does not support the older V2 scheme. I get an error when I try to put an object or read the bucket's keys.

InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.  [Condition of type ZS3::REQUEST-ERROR]

Maybe there is a way in ZS3 to work around this?

**Comment by xach** [comment]
There isn't a way to work around it in the current code. It will need
some updating across the board to work properly with new locations,
which do not support the legacy auth scheme.

I don't know when I'll be able to get to it, but I hope to do it
soon. (If you're in a hurry, you can get in touch with my employer,
Clozure Associates, to make it a paid priority.)

**Comment by exquisitus** [comment]
Thank you for your answer. I have been using s3 buckets in Ireland and I had decided to move them to Germany before I discovered this issue. But no, this move is not necessary for me.

**Comment by xach** [comment]
https://github.com/xach/zs3/tree/aws4-hmac-sha256 is a branch in progress that should fix the issue. Can you give it a try?

**Comment by xach** [comment]
This should be fixed in 1.2.8.
