### ISSUE TITLE
delete-object not using credentials

### ISSUE THREAD

**Issue by wsgac** [xach/zs3#16]
When creating a `DELETE` request in the `delete-object` function you're not providing the security token header, which results in the `InvalidAccessKeyId` error from Amazon (at least it did so in my case). Below is a small fix that worked for me:

    (defun delete-object (bucket key &key
                                       ((:credentials *credentials*) *credentials*))
      "Delete one object from BUCKET identified by KEY."
      (let ((security-token (security-token *credentials*)))
        (submit-request (make-instance 'request
                                       :method :delete
                                       :bucket bucket
                                       :key key
                                       :amz-headers
                                       (when security-token
                                         (list (cons "security-token" security-token)))))))

**Comment by xach** [comment]
I can't reproduce - I am able to delete objects without issue. And I also do not have a SECURITY-TOKEN function in my source code that I can find. Am I missing something?

**Comment by wsgac** [comment]
Oh, sorry. I was using a slightly modified version of your library with that function added. I don't know if it's a matter of access policy, but I was unable to delete objects without adding the `x-amz-mfa` header, which I believe has something to do with bucket versioning.
