### ISSUE TITLE
bucket-location failing for role-based credentials

### ISSUE THREAD

**Issue by wsgac** [xach/zs3#25]
I've noticed that on AWS EC2 instances with role-based credentials (i.e. including a security token) the call to `bucket-location` (and only this one function) fails with the error:
`Error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.`.
I found out that the missing part is the `x-amz-security-token` header. I managed to fix this behavior by adding the following keyword argument in `request` constructor, inside `bucket-location`:
```
:extra-http-headers
`(,(when (security-token *credentials*)
     (cons "x-amz-security-token"
           (security-token *credentials*))))
```
Do you want me to create a PR with this change?

**Comment by xach** [comment]
Yes, please. Thanks for the report.

**Comment by wsgac** [comment]
PR created.

**Comment by xach** [comment]
Committed, thanks again.

**Comment by wsgac** [comment]
Thank you.
