### ISSUE TITLE
credentials format changed or needs additional note in readme/examples?

### ISSUE THREAD

**Issue by sudodoki** [xach/zs3#28]
Seems that https://github.com/xach/zs3/blob/4acf54f26472fc211e519af4a9eb15fdf09896cb/credentials.lisp#L95-L100 relies on credentials to be just new line delimited values. Right now if you download file when generating key through amazon web interface, it would be file with .csv extension with contents
```
AWSAccessKeyId=%keyId%
AWSSecretKey=%key%
```

**Comment by sudodoki** [comment]
And yeah, if you use the file downloaded and try to invoke some fn, like `zs3:all-keys` you'll get error like
```
The value
  NIL
is not of type
  STRING
```
from `ZS3::SUBMIT-REQUEST`

**Comment by xach** [comment]
The format is not meant to match Amazon's format - it's a ZS3- specific simple "format" of one line for each part.

ZS3 could be adapted to also check for the Amazon format, but that's a different story.
